#!/usr/bin/env python3
"""Pull the Oscillator series artwork from SoundCloud into oscillator/img/covers.

Each episode's cover is read from the track page's og:image tag, so the list
below is just slugs — titles and artwork URLs come from SoundCloud itself and
stay correct if a cover is ever replaced. Re-runnable: existing files are
overwritten, so adding a slug and running again is all a new episode needs.

    python3 tools/fetch-oscillator-art.py
"""

import io
import json
import os
import re
import sys
import urllib.request

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "oscillator", "img", "covers")
DATA = os.path.join(ROOT, "oscillator", "assets", "js", "series.js")

PROFILE = "https://soundcloud.com/oscillatorr"
UA = "Mozilla/5.0 (compatible; facebookexternalhit/1.1)"

# newest first — the order the site lists them in
SLUGS = [
    "030-mahyar-arabiyan",
    "pooyan",
    "028-barbad",
    "027-del4raa",
    "026-kiarash",
    "025-traumatic",
    "024-xaxwave",
    "badador",
    "ronin",
    "021-dynno",
]

SIZE = 700  # covers render at most ~340 CSS px, so this stays above 2x


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def meta(html, prop):
    m = re.search(r'<meta property="%s" content="([^"]*)"' % re.escape(prop), html)
    return m.group(1) if m else ""


def main():
    os.makedirs(OUT, exist_ok=True)
    episodes = []

    for slug in SLUGS:
        try:
            html = get(f"{PROFILE}/{slug}").decode("utf-8", "replace")
        except Exception as err:                      # noqa: BLE001
            print(f"  {slug:24s} FAILED: {err}")
            continue

        title = meta(html, "og:title")
        art = meta(html, "og:image")
        if not art:
            print(f"  {slug:24s} no artwork found")
            continue

        # "#030-Mahyar Arabiyan" / "#029 - Pooyan" -> ("030", "Mahyar Arabiyan")
        m = re.match(r"#?\s*(\d+)\s*-\s*(.+)", title)
        number, name = (m.group(1), m.group(2).strip()) if m else ("", title)

        im = Image.open(io.BytesIO(get(art))).convert("RGB")
        side = min(im.size)
        im = im.crop(((im.width - side) // 2, (im.height - side) // 2,
                      (im.width - side) // 2 + side, (im.height - side) // 2 + side))
        if im.width > SIZE:
            im = im.resize((SIZE, SIZE), Image.LANCZOS)

        out = os.path.join(OUT, f"{number or slug}.webp")
        im.save(out, "WEBP", quality=86, method=6)
        episodes.append({
            "number": number,
            "artist": name,
            "cover": f"img/covers/{os.path.basename(out)}",
            "url": f"{PROFILE}/{slug}",
        })
        print(f"  {slug:24s} #{number:<4s} {name:<20s} {os.path.getsize(out)/1024:6.1f} KB")

    if not episodes:
        sys.exit("nothing fetched")

    with open(DATA, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/fetch-oscillator-art.py — do not edit by hand.\n"
                "   Titles and artwork come from the SoundCloud track pages. */\n")
        f.write("window.OSCILLATOR_SERIES = ")
        json.dump(episodes, f, indent=2, ensure_ascii=False)
        f.write(";\n")
    print(f"\n{len(episodes)} episodes -> {os.path.relpath(DATA, ROOT)}")


if __name__ == "__main__":
    main()
